workflows:
  default-workflow:
    name: Default Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      kotlin: "1.9.24"
      android_signing:
        - release_signing_config
    scripts:
      - name: Build Android App
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.apk
