workflows:
  android-workflow:
    name: Android Workflow
    environment:
      flutter: stable
      android_signing:
        - reference_key
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build App Bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
