workflows:
  android-workflow:
    name: Clean Flutter Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Recreate Android Project Directory
        script: |
          flutter create . --org com.aura --project-name aura_assistant --platforms android
      - name: Get Dependencies
        script: |
          flutter pub get
      - name: Build AppBundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
